-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 08:04:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ejemploProyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejemploProyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemploProyecto` DEFAULT CHARACTER SET utf8 ;
USE `ejemploProyecto` ;

-- -----------------------------------------------------
-- Table `ejemploProyecto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejemploProyecto`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` BIGINT UNSIGNED NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
